# DEPRECATED
FROM karmaresearch/wdps2

ENV VIRTUAL_ENV=/venv
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

# WORKDIR /

# COPY . .


# # RUN pipenv install --system --deploy --i

CMD ["python", "-u", "example_using_llm.py"]

